### ISSUE TITLE
[細かいですが]Project作成時に画像を指定しないと、サーバー側でエラー

### ISSUE THREAD

**Issue by ms2sato** [benrickken/crowdfunding-api#46]
ActiveSupport::MessageVerifier::InvalidSignature 
が発生します。検索するとあるあるっぽいので、時間のある時にでもちょっと見ておいてください（ActiveStorageでやるとよく起こるのかな？）

**Comment by benrickken** [comment]
https://groups.google.com/g/rubyonrails-core/c/xI5HPnxIAIE?pli=1
